### PR TITLE
fix(action/inject): prevent `cross-seed inject` if no client

### PR DESCRIPTION
**Pull request by ShanaryS**
Also updated `getClient()` to return null if no client is configured.

### CODE REVIEW

**Review by mmgoodnow — COMMENTED** [review]
I don't really see how changing it to `TorrentClient | null` helps anything if we have to force unwrap it with `!` every time we use it.

**Comment by ShanaryS** [comment]
It's necessary for the blocklist branch as the client get's used outside of injection, but I added it here so the diff is easier.

**Comment by mmgoodnow** [comment]
If you want a simpler diff, would you mind making the case for that in a separate PR?

**Comment by ShanaryS** [comment]
It's very straight forward so I don't think it's worth it. I might move all the new functions added to clients to it's out PR though. That would make the rest easier to review.

**Pull request merged**
