### PR TITLE
Respect `Retry-After` header in Torznab queries

### LINKED ISSUE #375: Respect Retry-After for grabs
https://github.com/cross-seed/cross-seed/blob/7486f190c2c893d4415e3fb75f12623bba896bca/src/torznab.ts#L431-L436

rather than assuming an hour; check and use the retry-after header

### PR DESCRIPTION
**Pull request by bakerboy448**
# ToDo

- [x] cleanup initial chatgpt code 😅
- [ ] Test
- [ ] verbose logging?

# Git Ref
- Fixes #375

### CODE REVIEW

**Comment by onedr0p** [comment]
I think the workflow needs to be updated to `pull_request_target` instead of `pull_request` so the tokens carry over.

https://github.com/cross-seed/cross-seed/blob/master/.github/workflows/ci.yml#L9

**Comment by mmgoodnow** [comment]
LGTM, lmk when you're ready for a merge.

**Comment by bakerboy448** [comment]
changes look good.  Probably should be tested, but also seems simple/logical enough to just Yeeet in 😅

**Comment by onedr0p** [comment]
Logic seems sound, unfortunate that we cannot test a container build of this PR. We should be able to make PRs build though without much a hassle.

**Comment by mmgoodnow** [comment]
yolo

**Pull request merged**
